pre_app_deploy:
 files:
  /etc/apache2/sites-enabled/vhost.conf:
    name: vhost.conf
    path: /etc/apache2/sites-enabled/
    mode: "0644"
    owner: root
    group: root
    content: |
      <VirtualHost *:80>
        DocumentRoot /var/www/html
        <Directory /var/www/html>
          AllowOverride All
          Order Allow,Deny
          Allow from All
        </Directory>

        CustomLog /var/log/apache2/access.log combined
        ErrorLog /var/log/apache2/error.log

      </VirtualHost>

 execs:
  Remove default apache site:
   name: Remove default apache site
   command: |
     rm -rf /etc/apache2/sites-enabled/000-default.conf
