exec_once:
 files:
  /etc/apache2/sites-enabled/jorani.conf:
    name: jorani.conf
    path: /etc/apache2/sites-enabled/
    mode: "0644"
    owner: root
    group: root
    content: |
      <VirtualHost *:80>
        DocumentRoot /var/www/html/jorani
        <Directory /var/www/html/jorani>
          AllowOverride All
          Order Allow,Deny
          Allow from All
        </Directory>

        CustomLog /var/log/apache2/access.log combined
        ErrorLog /var/log/apache2/error.log

      </VirtualHost>

 execs:
  Import Jorani Database:
   name: Import Jorani Database
   command: |
     #!/usr/bin/env bash
     . /opt/bunnyshell/package_secrets.sh
      sql_file='sql/lms.sql'
      sed -i -- "s/lms/${MYSQL__DATABASE_NAME}/g" ${sql_file}
      mysql --user="${MYSQL__DATABASE_USER}" --password="${MYSQL__USER_PASSWORD}" -D ${MYSQL__DATABASE_NAME} < ${sql_file}

  Configure Jorani:
   name: Configure Jorani
   command: |
     #!/usr/bin/env bash
     . /opt/bunnyshell/package_secrets.sh

     config_file='application/config/database.php'
     sed -i -- "s/'dsn'\t=>.*/'dsn'\t=> 'mysql:host=localhost;dbname=${MYSQL__DATABASE_NAME}',/g" ${config_file}
     sed -i -- "s/'hostname' => ''/'hostname' => 'localhost'/g" ${config_file}
     sed -i -- "s/'username' => ''/'username' => '${MYSQL__DATABASE_USER}'/g" ${config_file}
     sed -i -- "s/'password' => ''/'password' => '${MYSQL__USER_PASSWORD}'/g" ${config_file}
     sed -i -- "s/'database' => ''/'database' => '${MYSQL__DATABASE_NAME}'/g" ${config_file}

     openssl genrsa -out assets/keys/private.pem 1024
     openssl rsa -in assets/keys/private.pem -outform PEM -pubout -out assets/keys/public.pem

  Remove default apache config file:
   name: Remove default apache config file
   command: |
     rm -f /etc/apache2/sites-enabled/000-default.conf

pre_app_deploy:
 execs:
  Run composer install:
   name: Run composer install
   command: |
     #!/usr/bin/env bash
     export COMPOSER_HOME=/usr/local/bin/.composer
     /usr/local/bin/composer install

post_app_deploy:
 execs:
  Restart apache:
   name: Restart apache
   command: |
     #!/usr/bin/env bash
     chown -RL www-data:www-data /var/www/html/jorani
     service apache2 restart
