exec_once:
 execs:
  Import Jorani Database:
   name: Import Jorani Database
   command: |
     #!/usr/bin/env bash
     . /opt/bunnyshell/application_secrets.sh
      sql_file='sql/lms.sql'
      sed -i -- "s/lms/${DATABASE_NAME}/g" ${sql_file}
      mysql --user="${DATABASE_USER}" --password="${USER_PASSWORD}" -D ${DATABASE_NAME} < ${sql_file}

  Configure Jorani:
   name: Configure Jorani
   command: |
     #!/usr/bin/env bash
     . /opt/bunnyshell/application_secrets.sh

     config_file='application/config/database.php'
     sed -i -- "s/'dsn'\t=>.*/'dsn'\t=> 'mysql:host=localhost;dbname=${DATABASE_NAME}',/g" ${config_file}
     sed -i -- "s/'hostname' => ''/'hostname' => 'localhost'/g" ${config_file}
     sed -i -- "s/'username' => ''/'username' => '${DATABASE_USER}'/g" ${config_file}
     sed -i -- "s/'password' => ''/'password' => '${USER_PASSWORD}'/g" ${config_file}
     sed -i -- "s/'database' => ''/'database' => '${DATABASE_NAME}'/g" ${config_file}

     openssl genrsa -out assets/keys/private.pem 1024
     openssl rsa -in assets/keys/private.pem -outform PEM -pubout -out assets/keys/public.pem

pre_app_deploy:
 execs:
  Run composer install:
   name: Run composer install
   command: |
     #!/usr/bin/env bash
     export COMPOSER_HOME=/usr/local/bin/.composer
     /usr/local/bin/composer install

post_app_deploy:
 execs:
  Restart apache:
   name: Restart apache
   command: |
     #!/usr/bin/env bash
     chown -RL www-data:www-data /var/www/html/jorani
     service apache2 restart
